### ISSUE TITLE
[Fx Nightly 50.0a1 since jun-16! - Fix is on the way!] - Add-on not working (titlebar not hidden, etc)

### ISSUE THREAD

**Issue by testman42** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#317] opened 2016-06-16 22:18 UTC
I believe that something broke for me.
I'm using Firefox Nightly 50.0a1 on Fedora 23 x86_64
This is Nightly with this plugin disabled: http://i.imgur.com/HNEydvR.png
(works and looks as expected)
This is Nightly with this plugin enabled: http://i.imgur.com/P4rxkEu.png
(there should still be menu button and there should not be no title bar)

Any idea how to make it work again?

**Comment by Javier-DarthPalpatine** [comment] 2016-06-16 23:16
I have Fx Beta in Linux Mint and It's working well.  No Nightly to test in Linux (only in Windows)

Do you know if I can install Nightly on Linux Mint without interfering with my Beta and Stable Firefox?  Perhaps a Portable-like intall?
Tks!

**Comment by Javier-DarthPalpatine** [comment] 2016-06-16 23:18
Can you Test this in Fx Beta or Stable? 
(And I use Linux 32bit here, lets hope that won't be a problem to reproduce this)

**Comment by testman42** [comment] 2016-06-17 00:01
In Fx stable (47.0) it does both, removes title bar (as expected) and removes menu button (unexpected). If plugin is disabled, Fx behaves normally.

**Comment by Javier-DarthPalpatine** [comment] 2016-06-17 00:06
About menu button,  please make this option is checked:
    Look&Feel2 > "Show Firefox's Main Menu/Panel button"

I'm about to test Nightly on Linux...

**Comment by testman42** [comment] 2016-06-17 00:24
yes, I have that option checked

I just added HCTP into clean install of Nightly inside Linux Mint 18 virtual machine, with same result as in Fedora host, title bar still there but missing menu button.

**Comment by Javier-DarthPalpatine** [comment] 2016-06-17 00:31
**ISSUE IS CONFIRMED/Reproduced!** 
It seems to appear ONLY on **NIGHTLY since TODAY'S Build (2016-jun-16)**,  same on Windows and Linux!

**I'm trying a Fix already, will be released soon!**

**Closed** 2016-06-20 23:30 UTC
